In [72]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [73]:
df1=pd.read_csv('national_generation_capacity_stacked.csv')

In [74]:
data=df1[df1.country.isin(['DE','FR'])]

In [75]:
wblinks=data.weblink

In [76]:
data.drop(columns=['weblink'],inplace=True)

C:\Users\Siddhesh\AppData\Local\Temp\ipykernel_20332\1698080622.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop(columns=['weblink'],inplace=True)

In [77]:
data.capacity_definition.value_counts()

Unknown         1158
Net capacity     733
Name: capacity_definition, dtype: int64

In [78]:
data.reset_index(inplace=True)

In [79]:
data.drop(columns=['index'],inplace=True)

C:\Users\Siddhesh\AppData\Local\Temp\ipykernel_20332\2136747082.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop(columns=['index'],inplace=True)

In [80]:
data1=data

In [81]:
data1.drop(columns=['source','source_type','capacity_definition','comment'],inplace=True)

C:\Users\Siddhesh\AppData\Local\Temp\ipykernel_20332\228924561.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1.drop(columns=['source','source_type','capacity_definition','comment'],inplace=True)

In [82]:
data1=data1.sort_values(by=['year'])

In [83]:
france=data1[data1['country']=='FR']
germany=data1[data1['country']=='DE']

In [51]:
france.capacity.value_counts()

0.0         229
63130.0      32
240.0        25
2.0          14
6121.0        8
           ...
1194.0        1
32977.0       1
123510.0      1
7641.0        1
246.0         1
Name: capacity, Length: 520, dtype: int64

In [84]:
data1[data1.country=='DE']

,ID,technology,year,type,country,capacity,energy_source_level_0,energy_source_level_1,energy_source_level_2,energy_source_level_3,technology_level
140,3599,Other bioenergy and renewable waste,1990,Installed capacity in MW,DE,22.0,False,False,False,True,True
132,3591,Biomass and biogas,1990,Installed capacity in MW,DE,89.0,False,False,False,True,True
133,3592,Concentrated solar power,1990,Installed capacity in MW,DE,0.0,False,False,False,False,True
134,3593,Fossil fuels,1990,Installed capacity in MW,DE,68330.0,False,True,False,False,False
135,3594,Geothermal,1990,Installed capacity in MW,DE,0.0,False,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...
626,4085,Biomass and biogas,2016,Installed capacity in MW,DE,6070.0,False,False,False,True,True
636,4095,Pumped storage,2016,Installed capacity in MW,DE,5540.0,False,False,False,False,True
627,4086,Concentrated solar power,2016,Installed capacity in MW,DE,2.0,False,False,False,False,True
628,4087,Fossil fuels,2016,Installed capacity in MW,DE,88046.0,False,True,False,False,False
635,4094,Photovoltaics,2016,Installed capacity in MW,DE,40714.0,False,False,False,False,True

In [85]:
germany=germany[germany.capacity>0.0]
france=france[france.capacity>0.0]

In [87]:
france.drop(columns=['energy_source_level_0','energy_source_level_1','energy_source_level_2','energy_source_level_3'],inplace=True)
germany.drop(columns=['energy_source_level_0','energy_source_level_1','energy_source_level_2','energy_source_level_3'],inplace=True)

In [88]:
france

,ID,technology,year,type,country,capacity,technology_level
661,6172,Renewable energy sources,1990,Installed capacity in MW,FR,24913.0,False
655,6166,Pumped storage,1990,Installed capacity in MW,FR,1792.0,True
652,6163,Nuclear,1990,Installed capacity in MW,FR,55750.0,True
650,6161,Marine,1990,Installed capacity in MW,FR,240.0,True
662,6173,Differently categorized fossil fuels,1990,Installed capacity in MW,FR,22673.0,True
...,...,...,...,...,...,...,...
76,1083,Wind,2020,Installed capacity in MW,FR,16592.0,False
101,1463,Differently categorized solar,2020,Installed capacity in MW,FR,9438.0,True
50,775,Hydro,2020,Installed capacity in MW,FR,21603.0,False
117,1601,Biomass and biogas,2020,Installed capacity in MW,FR,1578.0,True
107,1524,Marine,2020,Installed capacity in MW,FR,246.0,True

In [91]:
germany.technology.value_counts()

Fossil fuels                                        38
Nuclear                                             38
Wind                                                38
Solar                                               38
Renewable energy sources                            38
Total                                               38
Hydro                                               38
Bioenergy and renewable waste                       36
Biomass and biogas                                  36
Differently categorized wind                        33
Differently categorized fossil fuels                33
Pumped storage                                      28
Other bioenergy and renewable waste                 27
Non-renewable waste                                 27
Photovoltaics                                       27
Differently categorized solar                       11
Geothermal                                          10
Concentrated solar power                             8
Differently categorized renewable energy sources     7
Other or unspecified energy sources                  7
Differently categorized hydro                        5
Natural gas                                          5
Lignite                                              5
Hard coal                                            5
Offshore                                             5
Onshore                                              5
Oil                                                  5
Run-of-river                                         3
Reservoir including pumped storage                   2
Reservoir                                            1
Name: technology, dtype: int64